services:
  typesense:
    image: typesense/typesense:29.0
    container_name: typesense
    ports:
      - "8108:8108"
    command: >
      --data-dir /data
      --api-key=${API_KEY_TYPESENSE}
      --enable-cors
    volumes:
      - typesense-data:/data
    networks:
      - typesense_net
    restart: unless-stopped

volumes:
  typesense-data:

networks:
  typesense_net:
    driver: bridge
